#!/bin/sh
while true; do
    BATTERY=$(cat /sys/class/power_supply/BAT0/capacity)
    DATE=$(date)
    xsetroot -name " [ ${BATTERY} % ] [ ${DATE} ] "
	sleep 1
done &

xbanish &
picom &

random_wallpaper.sh

exec dwm
