[theme]
primary            = "#928374"
secondary          = "#928374"
title              = "#928374"

playing            = "#282828"

background         = "#DBD3BC"
highlight          = "#DBD3BC"
error              = "#DBD3BC"
statusbar          = "#DBD3BC"
cmdline            = "#DBD3BC"
search_match       = "#DBD3BC"
playing_selected   = "#DBD3BC"

highlight_bg       = "#484848"
statusbar_bg       = "#484848"
cmdline_bg         = "#484848"
statusbar_progress = "#484848"

error_bg           = "#CC241D"
